name: Unzip File

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Unzip the file
      run: unzip -o <webly-flutter>.zip -d <your-destination-folder>

    - name: Commit unzipped files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Unzipped and added files"
        git push
